name: auto-sprint-loop-beads
description: "Beads (steveyegge/beads) loop: use bd as the canonical work queue. Auto-run issues in dependency order, with stop-mode (story/epic/project) stored in bd config."
author: "BMad"

config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
date: system-generated

# Beads is provided by the user's local install:
# - https://github.com/steveyegge/beads
# - CLI binary: bd
# bd auto-discovers its project database under .beads/

installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/auto-sprint-loop-beads"
instructions: "{installed_path}/instructions.xml"
validation: false
template: false

standalone: true