name: auto-sprint-loop
description: "Automated sprint loop (Beads-backed, resumable): create story → validate → fix story → dev → review → fix → repeat. Stop mode controllable: stop after 1 story, 1 epic, or whole project."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
date: system-generated
sprint_artifacts: "{config_source}:sprint_artifacts"
sprint_status: "{sprint_artifacts}/sprint-status.yaml || {output_folder}/sprint-status.yaml"

# Beads (steveyegge/beads) integration (bd CLI)
# Beads is initialized per-repo with `bd init` and stored under `.beads/`.

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/auto-sprint-loop"
instructions: "{installed_path}/instructions.xml"
validation: false
template: false

# Project context
project_context: "**/project-context.md"

standalone: true