name: sprint-planning-beads
description: "Beads (steveyegge/beads) sprint planning: parse epic files and create bd epics + child issues with dependencies (canonical tracker)."
author: "BMad"

config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/sprint-planning-beads"
instructions: "{installed_path}/instructions.md"
validation: false
template: false

variables:
  project_context: "**/project-context.md"
  epics_location: "{output_folder}"
  epics_pattern: "epic*.md"

input_file_patterns:
  epics:
    description: "All epics with user stories"
    whole: "{output_folder}/*epic*.md"
    sharded: "{output_folder}/*epic*/*.md"
    load_strategy: "FULL_LOAD"

standalone: true